import { pool } from '../../database/db'
import { useState } from 'react'
import Header from '../../components/Header'
import Image from 'next/image'
import RadioGroup from '@mui/material/RadioGroup';
import Radio from '@mui/material/Radio';
import FormControlLabel from '@mui/material/FormControlLabel'; 
import FormGroup from '@mui/material/FormGroup'; 
import Checkbox from '@mui/material/Checkbox'; 
import Rating from '@mui/material/Rating';
import { makeStyles } from '@mui/styles';

export const getStaticPaths = async () => {
    const res = await pool.query('SELECT * FROM universities')
    const data = await res.rows

    const paths = data.map(uni => {
        return {
            params: { slug: uni.uni_slug }
        }
    })

    return {
        paths,
        fallback: false
    }
}

export const getStaticProps = async (context) => {
    const slug = context.params.slug
    const res = await pool.query('SELECT * FROM universities WHERE uni_slug = $1', [slug])
    const data = await res.rows[0]

    return {
        props: { university: data }
    }
}

const useStyles = makeStyles({
    input: {
        // color: "#51ff00",
        "&.Mui-checked": {
            color: "#51ff00"
        }
    }
})

const University = ({ university }) => {
    const classes = useStyles()
    const { uni_id: id, uni_name: name, uni_slug: slug} = university
    const [isChecked, setIsChecked] = useState(true)

    return (
        <div className="university-page">
            <Header />
            <div className="banner">
                <Image
                    src={`/assets/uni-images/${id}.jpg`}
                    alt={`id`}
                    layout="fill"
                    objectFit="cover"
                />
            </div>
            <div className="uni-content">
                <div className="filter">
                    <h2>{name}</h2>
                    <div className="spacing">
                        <p>12 student reviews</p>
                    </div>
                    <div className="spacing">
                        <h5>Sort</h5>
                        <RadioGroup
                            aria-label="sort"
                            defaultValue="name"
                            name="sort"
                        >
                            <FormControlLabel value="name" control={<Radio className={classes.input} />} label="Name" />
                            <FormControlLabel value="highest-rated" control={<Radio className={classes.input} />} label="Highest Rated" />
                            <FormControlLabel value="most-reviews" control={<Radio className={classes.input} />} label="Most Reviews" />
                        </RadioGroup>
                    </div>
                    <div className="spacing">
                        <h5>Filter By Class</h5>
                        <RadioGroup
                            aria-label="class"
                            defaultValue="all"
                            name="class"
                        >
                            <FormControlLabel value="all" control={<Radio className={classes.input} />} label="All Years" />
                            <FormControlLabel value="first-year" control={<Radio className={classes.input} />} label="First Years" />
                            <FormControlLabel value="second-year" control={<Radio className={classes.input} />} label="Second Years" />
                            <FormControlLabel value="grad" control={<Radio className={classes.input} />} label="Third Years/Graduates" />
                            <FormControlLabel value="post-grad" control={<Radio className={classes.input} />} label="Post Graduates" />
                        </RadioGroup>
                    </div>
                    <div className="spacing">
                    <h5>Amenities</h5>
                        <p className="subtitle">generated by our reviewers</p>
                        <FormGroup>
                            <FormControlLabel
                                label="Dining Hall"
                                control={
                                    <Checkbox 
                                        value="dining-hall"
                                        className={classes.input} 
                                        onChange={
                                        (e) => console.log(e.target.checked, e.target.value)
                                    } />
                                }
                            />
                            <FormControlLabel
                                label="Air Conditioning"
                                control={
                                    <Checkbox 
                                        value="air-conditioning"
                                        className={classes.input} 
                                        onChange={
                                        (e) => console.log(e.target.checked, e.target.value)
                                    } />
                                }
                            />
                        </FormGroup>
                    </div>
                </div>
                <div className="residences">
                    <h3><span className="text">3 Residences</span> match your filters</h3>

                    <div className="residence-card-container">
                        <div className="residence-card">
                            <Image
                                src="/assets/ReviewAvatar.svg"
                                alt="house-svg"
                                width={75}
                                height={75}
                                className="residence-card-img"
                            />

                            <div className="residence-card-content">
                                <h4>Kovacs</h4>
                                <div className="rating-container">
                                    <Rating name="read-only" value={4.3} precision={0.25} readOnly />
                                    <p>4.3</p>
                                </div>
                                <p>2 reviews</p>
                            </div>
                        </div>
                        <div className="residence-card">
                            <Image
                                src="/assets/ReviewAvatar.svg"
                                alt="house-svg"
                                width={75}
                                height={75}
                                className="residence-card-img"
                            />

                            <div className="residence-card-content">
                                <h4>Long Name</h4>
                                <div className="rating-container">
                                    <Rating name="read-only" value={4.3} precision={0.25} readOnly />
                                    <p>4.3</p>
                                </div>
                                <p>2 reviews</p>
                            </div>
                        </div>
                        <div className="residence-card">
                            <Image
                                src="/assets/ReviewAvatar.svg"
                                alt="house-svg"
                                width={75}
                                height={75}
                                className="residence-card-img"
                            />

                            <div className="residence-card-content">
                                <h4>Random Very Long Name</h4>
                                <div className="rating-container">
                                    <Rating name="read-only" value={4.3} precision={0.25} readOnly />
                                    <p>4.3</p>
                                </div>
                                <p>2 reviews</p>
                            </div>
                        </div>
                        <div className="residence-card">
                            <Image
                                src="/assets/ReviewAvatar.svg"
                                alt="house-svg"
                                width={75}
                                height={75}
                                className="residence-card-img"
                            />

                            <div className="residence-card-content">
                                <h4>South Point</h4>
                                <div className="rating-container">
                                    <Rating name="read-only" value={4.3} precision={0.25} readOnly />
                                    <p>4.3</p>
                                </div>
                                <p>2 reviews</p>
                            </div>
                        </div>
                    </div>

                    <h2>Cant find Your Res? <span className="text click">Add it here</span></h2>
                </div>
            </div>
        </div>
    )
}

export default University
