import Head from 'next/head'
import Image from 'next/image'
import { pool } from '../database/db'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { FaSearch } from 'react-icons/fa';

{/* <Head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head> */}

export default function Home({ universities }) {
  const router = useRouter()
  // const uniName = universities.map(uni => uni.uni_name)
  const [search, setSearch] = useState('')

  return (
    <div id="homepage">
      <section className="hero">
        <Image 
          className="hero-image"
          src="/assets/hero.jpg"
          alt="Hero Image"
          layout="fill"
          objectFit="cover"
          loading="eager"
          quality={100}
        />
        <div className="hero-overlay">
          <div>
            <Image 
              src="/assets/logos/LogoWhite.svg"
              alt="Logo"
              className="hero-logo"
              width={233}
              height={34}
            />
          </div>

          <div className="hero-content-outer">
            <div className="hero-content-inner">
              <h2>Find the Student House that will become your next <span>Home</span></h2>

              <div className="hero-content-search-div">
                <input 
                  type="text"
                  placeholder="Find your university"
                  value={search}               
                  onChange={(e) => {
                    setSearch(e.target.value)
                  }}
                />
                <div className="search-icon">
                  <FaSearch 
                    className="icon"
                  />
                </div>
                {
                  search.length > 0 && (
                    <div className="hero-search-div">
                      {
                        universities
                          .filter(name => name.toLowerCase().includes(search.toLowerCase()))
                          .map(uni => {
                            const { name, slug } = uni

                          return <div key={name} onClick={() => router.push(`/universities/${slug}`)}>{name}</div>
                        })
                      }
                    </div>
                  )
                }
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <section className="home-content content-1">
        <div className="text">
          <div>
            <h3>
              Find the residence that’s best for <span>you</span>
            </h3>
            <p>
              Locating the residence that best suits your needs has never been easier. Read our student reviews and testimonials from a variety of South African universities.
            </p>
          </div>
        </div>
        <div className="img">
          <Image
            src="/assets/FirstHomeContentSvg.svg"
            alt="svg"
            width={729}
            height={565}
            layout="responsive"
          />
        </div>
      </section>
      
      <section className="home-content content-2">
        <div className="img">
          <Image
            src="/assets/SecondHomeContentSvg.svg"
            alt="svg"
            width={719}
            height={482}
            layout="responsive"
          />
        </div>
        <div className="text">
          <div>
            <h3>
              Tell us what you think about your <span>residence</span>
            </h3>
            <p>
              Share your opinion on the student housing options in South Africa’s top universities, what you liked and how they could be improved.
            </p>
          </div>
        </div>
      </section>

      <section className="home-universities-section">
        <h2>Universities in South Africa</h2>
        <div className="container">
          {
            universities.map(uni => {
              const { uni_id: id, uni_name: name, uni_slug: slug } = uni

              return (
                <div className="uni-card" key={id}>
                  <div className="uni-card-img" onClick={() => {
                    console.log(slug)
                    router.push(`/universities/${slug}`)
                  }}>
                    <Image
                      src={`/assets/uni-images/${id}.jpg`}
                      alt={name}
                      layout="fill"
                      objectFit="cover"
                    />
                  </div>
                  <h5>{name}</h5>
                </div>
              )
            })
          }
        </div>
      </section>
    </div>
  )
}

export const getStaticProps = async (context) => {
  const res = await pool.query('SELECT * FROM universities')
  const universities = await res.rows

  if (!universities) {
    return {
      notFound: true
    }
  }

  return {
    props: {
      universities
    }
  }
}